
version: '3.7'
services:

  mongo:
    image: mongo:4.4.2
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=root
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - "27017:27017"
    volumes:
      - /mongo:/data/db
 


  twitter:
    container_name: Extractor
    restart: always
   
    build:
        context: ./Extractor
    volumes:
      - ./Extractor:/app
  
    depends_on:
      - mongo
    links:
      - mongo
#

      #recuerda crear script para crear usuario de bd a utilizar

postgresql:

    image: 'postgres:13.2-alpine'
    container_name: postgresql
      environment:      
        - POSTGRES_USER=usuario
        - POSTGRES_PASSWORD=usuario
        - POSTGRES_DB=customer
      ports:
        - "5432:5432"