
version: '3.7'
services:
  mongo:
  
    image: mongo:4.4.2
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=root
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - "27017:27017"
    volumes:
      - /mongo:/data/db
 


  twitter:
    container_name: Extractor
    restart: always
   
    build:
        context: ./Extractor
    volumes:
      - ./Extractor:/app
  
    depends_on:
      - mongo
    links:
      - mongo

#
